### ISSUE TITLE
Package statements are ignored

### ISSUE THREAD

**Issue by sciurius** [abeltje/V#1]
`V` does not track `package` and `class` statements.

Also, embedded version numbers (added in perl 5.14 IIRC) are not recognized.

Assume `Foo.pm`:
````
our $VERSION = 1.1;
package Bar 1.2;
package Foo 1.3;
````

Results:
````
 % perl -Mlib=. -MV=Foo
Foo
        ./Foo.pm: 1.1
% perl -Mlib=. -MFoo -E 'say $Bar::VERSION'
1.2
% perl -Mlib=. -MFoo -E 'say $Foo::VERSION'
1.3
````

While many tools do this wrong, why not be the first to do it right?

**Comment by abeltje** [comment]
Resolved in **0.17**
